medikago/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_app.urls')),
    path('', include(('trigger_1.urls', 'trigger_1'), namespace='trigger_1')),
    path('resep-obat/', include('trigger_3.urls')),
    path('rscabang_poli/', include('rscabang_poli.urls'))
]

trigger_1/urls.py
from django.urls import path, include
from .views import *
from django.conf.urls import url

app_name = "trigger_1"

urlpatterns = [
    path('sesi-konsultasi/reservasi/', reservasi_sesi_konsultasi, name="reservasi_sesi_konsultasi"),
    path('sesi-konsultasi/', sesi_konsultasi, name="sesi_konsultasi"),
    path('rs-cabang/registrasi/', registrasi_rs_cabang, name="registrasi_rs_cabang"),
    path('rs-cabang/', rs_cabang, name="rs_cabang"),
    url(r'^sesi-konsultasi/delete/(?P<delete_id>[A-Za-z0-9]*)', delete_sk, name="delete_sk"),
    url(r'^sesi-konsultasi/update/(?P<update_id>[A-Za-z0-9]*)', update_sk, name="update_sk"),
    url(r'^rs-cabang/delete/(?P<delete_id>[A-Za-z0-9]*)', delete_rs, name="delete_rs"),
    url(r'^rs-cabang/update/(?P<update_id>[A-Za-z0-9]*)', update_rs, name="update_rs"),
]

trigger_1/models.py
from django.db import models

# Create your models here.

trigger_1/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from user_app.models import Pengguna, Pasien
from django.db.models.fields import BLANK_CHOICE_DASH
from .query import retrieve_all_no_rekam_medis

DUMMY_TRANSAKSI_CHOICES = []

class ReservasiSesiKonsultasiForm(forms.Form):
    pilihan = [(num, num) for num in retrieve_all_no_rekam_medis()]
    no_rekam_medis = forms.CharField(
        max_length=50, 
        required=True, 
        widget=forms.Select(
            choices=BLANK_CHOICE_DASH + pilihan,
            attrs={'id':'no_rekam_medis_choices'}))
    tanggal = forms.DateField(required=True)
    id_transaksi = forms.CharField(max_length=50, required=True, widget=forms.Select(attrs={'id':'transaksi_choices'}))

class UpdateSesiKonsultasiForm(forms.Form):
    tanggal = forms.CharField(max_length=50, required=True)
    status = forms.CharField(max_length=50, required=True, widget=forms.Select(choices=[('BOOKED', 'BOOKED'), ('MENUNGGU KONFIRMASI', 'MENUNGGU KONFIRMASI'), ('SELESAI', 'SELESAI')]))
    
class RegistrasiRSCabangForm(forms.Form):
    kode_rs = forms.CharField(max_length=50, required=True)
    nama = forms.CharField(max_length=50, required=True)
    tanggal_pendirian = forms.DateField()
    jalan = forms.CharField()
    nomor = forms.IntegerField()
    kota = forms.CharField(required=True)

class UpdateRSCabangForm(forms.Form):
    nama = forms.CharField(max_length=50, required=True)
    tanggal_pendirian = forms.DateField()
    jalan = forms.CharField()
    nomor = forms.IntegerField()
    kota = forms.CharField(required=True)
    

trigger_1/views.py
from django.shortcuts import render, redirect
from .forms import *
from user_app.models import Pengguna
from .query import *
from django.http import JsonResponse

# Create your views here.


def reservasi_sesi_konsultasi(request):
    if request.is_ajax():
        respons = {'id_transaksi': [value for value in retrieve_id_transaksi_given_nrm(request.GET.get('choices'))]}
        return JsonResponse(respons)
    elif request.method == 'POST':
        form = ReservasiSesiKonsultasiForm(request.POST)
        if form.is_valid():
            no_rekam_medis = request.POST['no_rekam_medis']
            tanggal = request.POST['tanggal']
            id_transaksi = request.POST['id_transaksi']

            insert_sesi_konsultasi(no_rekam_medis, tanggal, id_transaksi)

            return redirect('/sesi-konsultasi')
    else:
        form = ReservasiSesiKonsultasiForm()
        konten = {'form' : form,}
        return render(request, 'reservasi_sesi_konsultasi.html', konten)

def sesi_konsultasi(request):
    respon = retrieve_all_sesi_konsultasi()
    if request.user.is_authenticated:
        konten = {'title' : 'Ubah Status Laporan', 'respon' : respon}
        user = request.user
        if user.is_superuser:
            return render(request, 'sesi_konsultasi_admin.html', konten)
        else:
            profile = Pengguna.objects.filter(user=user.id)
            if profile[0].is_admin:
                return render(request, 'sesi_konsultasi_admin.html', konten)
    konten = {'title' : 'Lihat Status Laporan', 'respon' : respon}
    return render(request, 'sesi_konsultasi.html', konten)

def delete_sk(request, delete_id):
    delete_sesi_konsultasi(delete_id)

    return redirect('/sesi-konsultasi')

def update_sk(request, update_id):
    if request.method == 'POST':
        form = UpdateSesiKonsultasiForm(request.POST)
        if form.is_valid():
            new_tanggal = request.POST['tanggal']
            new_status = request.POST['status']

            update_sesi_konsultasi(update_id, new_tanggal, new_status)

            return redirect('/sesi-konsultasi')

    data = retrive_sesi_konsultasi(update_id)
    form = UpdateSesiKonsultasiForm(initial={'tanggal': data['tanggal'], 'status': data['status']})
    konten = {'title' : 'Lihat Status Laporan', 'form' : form, 'value' : data}

    return render(request, 'update_sesi_konsultasi.html', konten)

def registrasi_rs_cabang(request):
    if request.method == 'POST':
        form = RegistrasiRSCabangForm(request.POST)
        if form.is_valid():
            kode_rs = request.POST['kode_rs']
            nama = request.POST['nama']
            tgl = request.POST['tanggal_pendirian']
            jalan = request.POST['jalan']
            nomor = request.POST['nomor']
            kota = request.POST['kota']

            insert_rs_cabang(kode_rs, nama, tgl, jalan, nomor, kota)

            return redirect('/rs-cabang')

    if request.user.is_authenticated:
        form = RegistrasiRSCabangForm()
        konten = {'title' : 'Ubah Status Laporan', 'form' : form}
        user = request.user

        if user.is_superuser:
            return render(request, 'registrasi_rs_cabang.html', konten)
        else:
            profile = Pengguna.objects.filter(user=user.id)
            if profile[0].is_admin:
                return render(request, 'registrasi_rs_cabang.html', konten)
    return redirect('/rs-cabang')

def rs_cabang(request):
    respon = retrieve_all_rs_cabang()
    if request.user.is_authenticated:
        konten = {'title' : 'Ubah Status Laporan', 'respon' : respon}
        user = request.user
        # print(dir(username))
        if user.is_superuser:
            return render(request, 'rs_cabang_admin.html', konten)
        else:
            profile = Pengguna.objects.filter(user=user.id)
            if profile[0].is_admin:
                return render(request, 'rs_cabang_admin.html', konten)
    konten = {'title' : 'Lihat Status Laporan', 'respon' : respon}
    return render(request, 'rs_cabang.html', konten)

def delete_rs(request, delete_id):
    delete_rs_cabang(delete_id)

    return redirect('/rs-cabang')

def update_rs(request, update_id):
    if request.method == 'POST':
        form = UpdateRSCabangForm(request.POST)
        if form.is_valid():
            new_nama = request.POST['nama']
            new_tgl = request.POST['tanggal_pendirian']
            new_jalan = request.POST['jalan']
            new_nomor = request.POST['nomor']
            new_kota = request.POST['kota']

            update_rs_cabang(update_id, new_nama, new_tgl, new_jalan, new_nomor, new_kota)

            return redirect('/rs-cabang')

    data = retrieve_rs_cabang(update_id)
    form = UpdateRSCabangForm(initial={
        'nama': data['nama'],
        'tanggal_pendirian': data['tanggal_pendirian'],
        'jalan': data['jalan'],
        'nomor': data['nomor'],
        'kota': data['kota'],
        })
    konten = {'title' : 'Lihat Status Laporan', 'form' : form, 'value' : data}

    return render(request, 'update_rs_cabang.html', konten)

trigger_1/templates/registrasi_rs_cabang.html
{% extends 'template.html' %}
{% load staticfiles%}
{% block content %}
<h3>FORM REGISTRASI RS CABANG</h3>
<form method="POST" class="post-form">
    <br>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Save</button>
</form>
{% endblock content %}
{% block js %}
{% endblock %}

trigger_1/templates/reservasi_sesi_konsultasi.html
{% extends 'template.html' %}
{% load staticfiles%}
{% block content %}
<h3>FORM RESERVASI SESI KONSULTASI</h3>
<form method="POST" class="post-form">
    <br>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Save</button>
</form>
{% endblock content %}
{% block js %}
<script>
    $(document).ready(function(){
        $("#no_rekam_medis_choices").change(function(){
            $.ajax({
                url: '',
                type: 'get',
                dataType: 'json',
                contentType: 'json',
                data: {
                    choices:  $("#no_rekam_medis_choices").val()
                },
                success: function(data){
                    var $transaksi_choices = $("#transaksi_choices");
                    $transaksi_choices.empty();
                    count = 0
                    for (i = 0; i < data.id_transaksi.length; i++){
                        value = data.id_transaksi[i]
                        $transaksi_choices.append('<option id=' + count++ + ' value=' + value + '>' + value + '</option>');
                    };
                },
                error: function (res) {
                     alert(res.status);                                                                                                                     
                }
                })
    })
    });
</script>
{% endblock %}

trigger_1/templates/rs_cabang.html
{% extends 'template.html' %}
{% load staticfiles%}
{% block content %}
<br>
<h3 class="text-center">LIST RS CABANG</h3>
<br>
<table class="table" id="table_ubah_laporan">
  <thead class="thead-light">
    <tr>
      <th class="text-center" scope="col">Kode RS</th>
      <th class="text-center" scope="col">Nama RS</th>
      <th class="text-center" scope="col">Tanggal Pendirian</th>
      <th class="text-center" scope="col">Jalan</th>
      <th class="text-center" scope="col">Nomor</th>
      <th class="text-center" scope="col">Kota</th>
    </tr>
  </thead>
  <tbody>
      {% for cell in respon %}
      <tr>
          <td class="text-center">{{cell.kode_rs}}</td>
          <td class="text-center">{{cell.nama}}</td>
          <td class="text-center">{{cell.tanggal_pendirian}}</td>
          <td class="text-center">{{cell.jalan}}</td>
          <td class="text-center">{{cell.nomor}}</td>
          <td class="text-center">{{cell.kota}}</td>
      </tr>
      {% endfor %}
  </tbody>
</table>
{% endblock content %}
{% block js %}
{% endblock %}

trigger_1/templates/rs_cabang_admin.html
{% extends 'template.html' %}
{% load staticfiles%}
{% block content %}
<br>
<h3 class="text-center">LIST RS CABANG</h3>
<br>
<table class="table" id="table_ubah_laporan">
  <thead class="thead-light">
    <tr>
      <th class="text-center" scope="col">Kode RS</th>
      <th class="text-center" scope="col">Nama RS</th>
      <th class="text-center" scope="col">Tanggal Pendirian</th>
      <th class="text-center" scope="col">Jalan</th>
      <th class="text-center" scope="col">Nomor</th>
      <th class="text-center" scope="col">Kota</th>
      <th class="text-center" scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
      {% for cell in respon %}
      <tr>
          <td class="text-center">{{cell.kode_rs}}</td>
          <td class="text-center">{{cell.nama}}</td>
          <td class="text-center">{{cell.tanggal_pendirian}}</td>
          <td class="text-center">{{cell.jalan}}</td>
          <td class="text-center">{{cell.nomor}}</td>
          <td class="text-center">{{cell.kota}}</td>
          <td>
          <a  class="btn btn-danger btn-sm" href="{% url 'trigger_1:delete_rs' cell.kode_rs %}">delete</a>
          <a class="btn btn-sm btn-outline-primary" href="{% url 'trigger_1:update_rs' cell.kode_rs %}"> Edit</a>
          </td>
      </tr>
      {% endfor %}
  </tbody>
</table>
{% endblock content %}
{% block js %}
{% endblock %}

trigger_1/templates/sesi_konsultasi.html
{% extends 'template.html' %}
{% load staticfiles%}
{% block content %}
<br>
<h3 class="text-center">LIST SESI KONSULTASI</h3>
<br>
<table class="table" id="table_ubah_laporan">
                <thead class="thead-light">
                  <tr>
                    <th class="text-center" scope="col">ID Konsultasi</th>
                    <th class="text-center" scope="col">Nomor Pasien</th>
                    <th class="text-center" scope="col">Tanggal</th>
                    <th class="text-center" scope="col">Biaya</th>
                    <th class="text-center" scope="col">Status</th>
                    <th class="text-center" scope="col">ID Transaksi</th>
                  </tr>
                </thead>
                <tbody>
                    {% for cell in respon %}
                    <tr>
                        <td class="text-center">{{cell.id_konsultasi}}</td>
                        <td class="text-center">{{cell.no_rekam_medis_pasien}}</td>
                        <td class="text-center">{{cell.tanggal}}</td>
                        <td class="text-center">{{cell.biaya}}</td>
                        <td class="text-center">{{cell.status}}</td>
                        <td class="text-center">{{cell.id_transaksi}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
{% endblock content %}
{% block js %}
{% endblock %}

trigger_1/templates/sesi_konsultasi_admin.html
{% extends 'template.html' %}
{% load staticfiles%}
{% block content %}
<br>
<h3 class="text-center">LIST SESI KONSULTASI</h3>
<br>    
<table class="table" id="table_ubah_laporan">
                <thead class="thead-light">
                  <tr>
                    <th class="text-center" scope="col">ID Konsultasi</th>
                    <th class="text-center" scope="col">Nomor Pasien</th>
                    <th class="text-center" scope="col">Tanggal</th>
                    <th class="text-center" scope="col">Biaya</th>
                    <th class="text-center" scope="col">Status</th>
                    <th class="text-center" scope="col">ID Transaksi</th>
                    <th class="text-center" scope="col">Action</th>
                  </tr>
                </thead>
                <tbody>
                    {% for cell in respon %}
                    <tr>
                        <td class="text-center">{{cell.id_konsultasi}}</td>
                        <td class="text-center">{{cell.no_rekam_medis_pasien}}</td>
                        <td class="text-center">{{cell.tanggal}}</td>
                        <td class="text-center">{{cell.biaya}}</td>
                        <td class="text-center">{{cell.status}}</td>
                        <td class="text-center">{{cell.id_transaksi}}</td>
                        <td>
                        {%csrf_token%}
                        <a  class="btn btn-danger btn-sm" href="{% url 'trigger_1:delete_sk' cell.id_konsultasi %}">delete</a>
                        <a class="btn btn-sm btn-outline-primary" href="{% url 'trigger_1:update_sk' cell.id_konsultasi %}"> Edit</a>
                        </td>
                    </tr>
                    {% endfor %} 
                </tbody>
            </table>
{% endblock content %}
{% block js %}
{% endblock %}

trigger_1/templates/update_rs_cabang.html
{% extends 'template.html' %}
{% load staticfiles%}
{% block content %}
<form method="POST" class="post-form">
    <br>
    {% csrf_token %}
    <label>Kode RS:</label>
    <input type="text" name="kode_rs" value="{{value.kode_rs}}" disabled></input>
    <br>
    {{ form.nama.label_tag }}
    {{ form.nama }}
    <br>
    {{ form.tanggal_pendirian.label_tag }}
    {{ form.tanggal_pendirian }}
    <br>
    {{ form.jalan.label_tag }}
    {{ form.jalan }}
    <br>
    {{ form.nomor.label_tag }}
    {{ form.nomor }}
    <br>
    {{ form.kota.label_tag }}
    {{ form.kota }}
    <br>
    <button type="submit" class="btn btn-primary">Save</button>
</form>
{% endblock content %}
{% block js %}
{% endblock %}

trigger_1/templates/update_sesi_konsultasi.html
{% extends 'template.html' %}
{% load staticfiles%}
{% block content %}
<form method="POST" class="post-form">
    <br>
    {% csrf_token %}
    <label>ID Konsultasi:</label>
    <input type="text" name="id_konsultasi" value="{{value.id_konsultasi}}" disabled></input>
    <br>
    <label>No Rekam Medis:</label>
    <input type="text" name="no_rekam_medis" value="{{value.no_rekam_medis_pasien}}" disabled></input>
    <br>
    <label>{{ form.tanggal.label_tag }}</label>
    {{form.tanggal}}
    <br>
    <label>Biaya:</label>
    <input type="text" name="biaya" value="{{value.biaya}}" disabled></input>
    <br>
    <label>{{ form.status.label_tag }}</label>
    {{form.status}}
    <br>
    <label>ID Transaksi:</label>
    <input type="text" name="id_transaksi" value="{{value.id_transaksi}}" disabled></input>
    <br>
    <button type="submit" class="btn btn-primary">Save</button>
</form>
{% endblock content %}
{% block js %}
{% endblock %}