medikago/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_app.urls')),
    path('', include(('trigger_1.urls', 'trigger_1'), namespace='trigger_1')),
    path('resep-obat/', include('trigger_3.urls')),
    path('rscabang_poli/', include('rscabang_poli.urls'))
]

trigger_1/urls.py
from django.urls import path, include
from .views import *
from django.conf.urls import url

app_name = "trigger_1"

urlpatterns = [
    path('sesi-konsultasi/reservasi/', reservasi_sesi_konsultasi, name="reservasi_sesi_konsultasi"),
    path('sesi-konsultasi/', sesi_konsultasi, name="sesi_konsultasi"),
    path('rs-cabang/registrasi/', registrasi_rs_cabang, name="registrasi_rs_cabang"),
    path('rs-cabang/', rs_cabang, name="rs_cabang"),
    url(r'^sesi-konsultasi/delete/(?P<delete_id>[A-Za-z0-9]*)', delete_sk, name="delete_sk"),
    url(r'^sesi-konsultasi/update/(?P<update_id>[A-Za-z0-9]*)', update_sk, name="update_sk"),
    url(r'^rs-cabang/delete/(?P<delete_id>[A-Za-z0-9]*)', delete_rs, name="delete_rs"),
    url(r'^rs-cabang/update/(?P<update_id>[A-Za-z0-9]*)', update_rs, name="update_rs"),
]

user_app/urls.py
from django.urls import path
from django.conf.urls import url
from .views import landing, signup, login_view
from django.contrib.auth.views import LogoutView
from django.conf import settings

urlpatterns = [
    path('', landing, name='landing'),
    path('masuk', login_view, name='login'),
    path('daftar/', signup, name='daftar'),
    url(r'^keluar/$', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout')
]

user_app/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser

# Create your models here.
class Pengguna(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,  primary_key=True)
    nama_lengkap = models.CharField(max_length=50, blank= False, null=True)
    nomor_id = models.CharField(max_length=50, blank= False, null=True)
    tanggal_lahir = models.DateField(blank= False, null=True)
    alamat = models.TextField(blank= False, null=True)
    is_dokter = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    is_pasien = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

class Dokter(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    id_dokter =  models.CharField(max_length=50, blank= False, primary_key=True)
    no_sip =  models.CharField(max_length=50, blank= False, null=True)
    spesialisasi = models.TextField(blank= False, null=True)

    def __str__(self):
        return self.user.username

class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nomor_pegawai = models.CharField(max_length=50, blank= False, primary_key=True)
    # kode_rs = models.CharField(max_length=50, blank= False, null=True)  --TIDAK ADA HRSNYA--

    def __str__(self):
        return self.user.username

class Pasien(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    no_rekam_medis = models.CharField(max_length=50, blank= False, primary_key=True)
    nama_asuransi = models.CharField(max_length=50, blank= False, null=True)

    def __str__(self):
        return self.user.username

user_app/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class SignUpForm(UserCreationForm):
    nama_lengkap = forms.CharField(max_length=50, required=True)
    nomor_id = forms.CharField(max_length=50, required=True)
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
    tanggal_lahir = forms.DateField(required=True)
    alamat = forms.CharField(widget=forms.Textarea, required=True)
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )

class DokterSignUpForm(SignUpForm):
    id_dokter = forms.CharField(max_length=50, required=True)
    no_sip = forms.CharField(max_length=50, required=True)
    spesialisasi = forms.CharField(widget=forms.Textarea, required=True)

class AdminSignUpForm(SignUpForm):
    nomor_pegawai = forms.CharField(max_length=50, required=True)
    # kode_rs = forms.CharField(max_length=50, required=True)  --TIDAK ADA HRSNYA--

class PasienSignUpForm(SignUpForm):
    no_rekam_medis =  forms.CharField(max_length=50, required=True)
    nama_asuransi =  forms.CharField(max_length=50, required=True)

class LoginForm(forms.Form):
    """Form for user login. Includes username for login and password
    for login. Also created function to test password length"""

    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class':'form-control form-custom',
            'placeholder':'Username',
            'name':'username'
        }
    ))

    password = forms.CharField(min_length=8, widget=forms.PasswordInput(
        attrs={
            'class':'form-control form-custom',
            'placeholder':'Password',
            'name':'password'
        }
    ))

user_app/views.py
from django.shortcuts import render, redirect, reverse
# from django.http import (
#     HttpResponseNotAllowed, HttpResponseRedirect,
#     HttpResponseForbidden, HttpResponseNotFound,
# )
from django.contrib.auth import login as dj_login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .forms import LoginForm, SignUpForm, DokterSignUpForm, PasienSignUpForm, AdminSignUpForm
from django.db import connection

def get_user_role(username, pswd):
    with connection.cursor() as cur:
        cur.execute("select * from dokter where username='{username}'".format(username=username))
        dokter = cur.fetchone()
        if(dokter):
            cur.close()
            return {'role':'Dokter', 'data':dokter}

        cur.execute("select * from administrator where username='{username}'".format(username=username))
        admin = cur.fetchone()
        if(admin):
            cur.close()
            return {'role':'Administrator', 'data':admin}

        cur.execute("select * from pasien where username='{username}'".format(username=username))
        pasien = cur.fetchone()
        if(pasien):
            cur.close()
            return {'role':'Pasien', 'data':pasien}
        
        cur.close()

def landing(request):
    return render(request, 'landing.html')

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            dj_login(request, user)
            return redirect('home')
    else:
        dokter_form = DokterSignUpForm()
        admin_form = AdminSignUpForm()
        pasien_form = PasienSignUpForm()
    return render(request, 'signup.html', {
        'admin_form' : admin_form,
        'dokter_form' : dokter_form,
        'pasien_form' : pasien_form
        })

def login_view(request):

    if(request.method == 'POST'):
        form = LoginForm(request.POST)

        username = request.POST['username']
        password = request.POST['password']
        with connection.cursor() as cur:
            cur.execute("select * from pengguna where username='{username}' and password='{pswd}';".format(username=username, pswd=password))
            user = cur.fetchone()
            print(user)
            cur.close()

        if(user is not None):  
            role = get_user_role(user[1], user[2])
            print(role)
            user = {
                'is_authenticated':True,
                'role': role['role'],
                'email':user[0],
                'username':user[1],
                'nama_lengkap':user[3],
                'nomor_id':user[4],
                'tanggal_lahir':user[5],
                'alamat':user[6],
                'specific_role':role['data']
            }

            request.session['user'] = user
            request.session.set_expiry(7200)

            return redirect("/")
        return redirect('/masuk')

    else:
        form = LoginForm()
    return render(request, 'login.html', {'form':form})

def keluar(request):
    logout(request)
    return redirect(reverse(login_view))

user_app/templates/landing.html
{% extends 'template.html' %}
{% load static %}
{% block content %}
<div class="main">
    <div class="my-5 landing-text">
        <h1>MedikaGO:</h1>
        <h2>Layanan Medis Super Cepat dan Mudah </h2>
        <p style="font-size: 12pt;" class="my-3">Sebuah inovasi platform online yang mempermudah kamu berkonsultasi dan mendiagnosa
            kesehatanmu dengan tim profesional di luar sana.
        </p>
        {% if request.session.user.is_authenticated %}
        {% else %}
        <a href="/daftar" class="my-4 px-5 py-2 btn btn-info">Daftar</a>
        {% endif %}
    </div>
    <img src="{% static 'landing-img.svg' %}" alt="" id="landing-img">
</div>
{% endblock %}

user_app/templates/login.html
{% extends 'template.html' %}
{% load static %}
{% block content %}
{% if request.session.user.is_authenticated %}
<a href="/">kembali ke halaman utama</a>
{% else %}
<div class="content-login">
    <div class="box-container flex-col-center min30vw">
        <div class="logo-container m-5">
            <a href="{% url 'landing' %}">
                <img src="{% static 'logo.svg' %}" alt="" id="logo">
            </a>
        </div>
        <div class="form-container ">
            <form action="" method="POST" class="flex-col-center">
                {% csrf_token %}
                <div class="form-unit my-1 mx-4">
                    <label for="username">Username:</label>
                    {{form.username}}
                </div>
                
                <div class="form-unit my-1 mx-4">
                    <label for="password">Password:</label>
                    {{form.password}}
                </div>

                <div class="form-unit mt-3 mb-5 mx-4 ">
                    <button type="submit" class="btn btn-submit">Masuk</button>
                </div>

            </form>
        </div>
    </div>

    <div class="box-container flex-col-center min30vw mt-3">
        <p style="font-size: 12pt;" class='m-4'>Belum punya akun? <a href="/daftar">Buat akun</a></p>
    </div>
</div>
{% endif %}

{% endblock %}

user_app/templates/signup.html
{% extends 'template.html' %}
{% load staticfiles%}
{% block content %}
{% if request.session.user.is_authenticated %}
<a href="/">kembali ke halaman utama</a>
{% else %}
    <div class="container col-6 border">
        <div class="container form-container">
            <div class="container form-head">
                <img src="" alt="" class="img-fluid">
                <p class="text-center">Kamu mau daftar sebagai apa ?</p>
            </div>
            <div class="container form-content">
                <div class="role-button d-flex dokter">
                    <img src="{% static 'logo-dokter.svg' %}" alt="" class="img-fluid form-role-logo">
                    <p class="">Dokter</p>
                    <form method="post">
                        {% csrf_token %}
                        {{ dokter_form.as_p }}
                    </form>
                </div>
                <div class="role-button d-flex admin">
                    <img src="{% static 'logo-admin.svg' %}" alt="" class="img-fluid form-role-logo">
                    <p>Admin</p>
                    <form method="post">
                        {% csrf_token %}
                        {{ admin_form.as_p }}
                    </form>
                </div>
                <div class="role-button d-flex pasien">
                    <img src="{% static 'logo-pasien.svg' %}" alt="" class="img-fluid form-role-logo">
                    <p>Pasien</p>
                    <form method="post">
                        {% csrf_token %}
                        {{ pasien_form.as_p }}
                    </form>
                </div>

            </div>
            <div class="container form-footer justify-content-between d-flex">
                <a href="" class="back-button">
                </a>
                <div class="progressbar">
                    <span class="dot current"></span>
                    <span class="dot"></span>
                </div>
                <div class="submit-button">
                </div>
            </div>
        </div>
    </div>
{% endif %}
{% endblock content %}
{% block js %}
<script src="{% static 'signup.js' %}"></script>
{% endblock %}

user_app/templates/template.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>MedikaGO</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|PT+Serif:400,700&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link rel="stylesheet" href="{% static 'signup.css' %}">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light sticky-top" style="text-align: center;">
        <a class="navbar-brand" href="{% url 'landing' %}">
            <img src="{% static 'logo.svg' %}" alt="" id="logo" class="my-2">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active mx-1">
                    <a class="nav-link" href="{% url 'landing' %}">Home <span class="sr-only">(current)</span></a>
                </li>   

                {% if request.session.user.is_authenticated %}
                <li class="nav-item mx-1">
                    <div class="dropdown">
                        <a class="nav-link dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                          RS Cabang
                        </a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            {% if request.session.user.role == "Administrator" %}
                            <a class="dropdown-item" href="#">Buat RS Cabang</a>
                            <a class="dropdown-item" href="{% url 'trigger_1:rs_cabang' %}">List RS Cabang</a>
                            <a class="dropdown-item" href="{% url 'daftarkan_dokter' %}">Daftarkan Dokter</a>
                            <a class="dropdown-item" href="{% url 'list_dokter_rscbg' %}">List Dokter RS Cabang</a>
                            <a class="dropdown-item" href="#">Daftarkan Administrator</a>
                            {% else %}
                            <a class="dropdown-item" href="{% url 'trigger_1:rs_cabang' %}">List RS Cabang</a>
                            <a class="dropdown-item" href="{% url 'list_dokter_rscbg' %}">List Dokter RS Cabang</a>
                            {% endif %}
                        </div>
                    </div>
                </li>

                <li class="nav-item mx-1">
                    {% if request.session.user.role == "Administrator" %}
                    <div class="dropdown">
                        <a class="nav-link dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            Sesi Konsultasi
                        </a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="{% url 'trigger_1:reservasi_sesi_konsultasi' %}">Buat Sesi Konsultasi</a>
                            <a class="dropdown-item" href="{% url 'trigger_1:sesi_konsultasi' %}">List Sesi Konsultasi</a>
                        </div>
                    </div>
                    {% else %}
                    <a class="nav-link" href="{% url 'trigger_1:sesi_konsultasi' %}">Sesi Konsultasi</a>
                    {% endif %}
                </li>

                <li class="nav-item mx-1">
                    <a class="nav-link" href="/tindakan">Tindakan</a>
                </li>

                <li class="nav-item mx-1">
                    <a class="nav-link" href="/tindakanpoli">Tindakan Poli</a>
                </li>

                {% if request.session.user.role == "Administrator" %}
                <li class="nav-item mx-1">
                    <div class="dropdown">
                        <a class="nav-link dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                           Poliklinik
                        </a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="{% url 'buat_layanan_poli' %}">Buat Layanan Poliklinik</a>
                            <a class="dropdown-item" href="{% url 'list_layanan_poli' %}">List Layanan Poliklinik</a>
                            <a class="dropdown-item" href="/">Buat Jadwal Poliklinik</a>
                            <a class="dropdown-item" href="{% url 'list_jadwal_poli' %}">List Jadwal Poliklinik</a>
                        </div>
                    </div>
                </li>
                {% endif %}

                
                <li class="nav-item mx-1" style="display: flex; flex-direction: column; align-items: center; justify-content: center;">
                    <div class="btn-group nav-item mx-1" >
                        <a style="margin: 0; cursor: pointer;" class="dropdown-toggle nav-link" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Resep & Obat
                        </a>
                        <div class="dropdown-menu">
                          <a class="dropdown-item" href="/resep-obat">Apotek</a>
                          <div class="dropdown-divider"></div>
                          {% if request.session.user.role == "Administrator" %}
                          <a class="dropdown-item" href="/resep-obat/resep/buat">Buat Resep</a>
                          {% endif %}   
                          <a class="dropdown-item" href="/resep-obat/resep">Cek Resep</a>
                          <div class="dropdown-divider"></div>
                          {% if request.session.user.role == "Administrator" %}
                          <a class="dropdown-item" href="/resep-obat/obat/buat">Buat Obat</a>
                          {% endif %}   
                          <a class="dropdown-item" href="/resep-obat/obat">Cek Obat</a>
                        </div>
                    </div>
                </li>
                <li class="nav-item mx-1">
                    <a class="nav-link" href="/">Transaksi</a>
                </li>
                {% endif %}  

                {% if request.session.user.is_authenticated %}
                <li class="nav-item mx-1">
                    <b><a class="nav-link" href="/">Profil</a></b>
                </li>
                <li class="nav-item mx-1">
                    <b><a class="nav-link" href="/keluar">Keluar</a></b>
                </li>
                {% else %}
                <li class="nav-item mx-1">
                    <b><a class="nav-link" href="/masuk">Masuk</a></b>
                </li>
                <li class="nav-item mx-1">
                    <b><a class="nav-link" href="/daftar">Daftar</a></b>
                </li>
                {% endif %}

            </ul>
        </div>
    </nav>

    <div class="main-content">
        {% block content %}
        {% endblock %}
    </div>
    <script
    src="https://code.jquery.com/jquery-3.5.1.js"
    integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
    crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script type="text/javascript" src="../static/query.js"></script>
    <script src="{% static 'datepicker.js'%}"></script>
    <script>

    </script>
        {% block js %}
        {% endblock %}

</body>

</html>